src/main/java/br/edu/ifpb/sace/bean/OfertaEstagioBean.java
package br.edu.ifpb.sace.bean;

import java.util.List;

import br.edu.ifpb.sace.dao.EmpresaDAO;
import br.edu.ifpb.sace.dao.OfertaEstagioDAO;
import br.edu.ifpb.sace.dao.PersistenceUtil;
import br.edu.ifpb.sace.entity.Empresa;
import br.edu.ifpb.sace.entity.OfertaEstagio;

public class OfertaEstagioBean {
	
	public List<OfertaEstagio> getOfertasEstagio() {
		OfertaEstagioDAO dao = new OfertaEstagioDAO(PersistenceUtil.getCurrentEntityManager());
		List<OfertaEstagio> ofertas = dao.findAll();
		return ofertas;
	}
	
	public List<OfertaEstagio> getOfertasEstagio(String id) {
		
		Empresa empresa = new Empresa();
		empresa.setId(Integer.parseInt(id));
		
		return getOfertasEstagio(empresa);
	}
	
	public List<OfertaEstagio> getOfertasEstagio(Object obj) {
		
		if(!(obj instanceof Empresa)) return null;
		
		EmpresaDAO dao = new EmpresaDAO(PersistenceUtil.getCurrentEntityManager());
		Empresa empresa = dao.find(((Empresa)obj).getId());
		
		return empresa.getOfertadasEstagio();
	}
	
}

src/main/java/br/edu/ifpb/sace/entity/OfertaEstagio.java
package br.edu.ifpb.sace.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.edu.ifpb.sace.abstractentity.AbstractEstagio;
import br.edu.ifpb.sace.util.StatusOfertaEstagio;

@Entity
public class OfertaEstagio extends AbstractEstagio {
	
	@Column(name="REQUISITOS")
	private String requisitos;
	
	@Column(name="QTDE_VAGAS")
	private int qtdeVaga;
	
	@OneToMany(cascade=CascadeType.ALL)
	@Column(name="CURSOS")
	private List<Curso> cursos;
	
	@Column(name="TELEFONE_CONTATO")
	private String telefoneContato;

	@Column(name="EMAIL_CONTATO")	
	private String emailContato;
	
	@ManyToMany(cascade=CascadeType.ALL)
	@JoinTable(name = "SELECIONDADO_OFT_ESTAGIO",
	joinColumns = { @JoinColumn(name = "ESTAGIO_ID") }, 
	inverseJoinColumns = { @JoinColumn(name = "PESSOA_ID") })
	@Column(name="CONDIDATOS")
	private List<Aluno> candidatos;
	
	@OneToMany(cascade=CascadeType.ALL)
	@Column(name="SELECIONADOS")
	private List<Aluno> selecionados;
	
	@Column(name="STATUS")
	private StatusOfertaEstagio status;

	@Temporal(TemporalType.DATE)
	@Column(name="VIGENCIA")
	private Date vigencia;
	
	@OneToMany
	@Column(name="ESTAGIOS")
	private List<Estagio> estagios;
		
	public OfertaEstagio(){
		this.candidatos = new ArrayList<Aluno>();
		this.selecionados = new ArrayList<Aluno>();
		this.status = StatusOfertaEstagio.AGUARDANDO;
	}

	public String getRequisitos() {
		return requisitos;
	}

	public void setRequisitos(String requisitos) {
		this.requisitos = requisitos;
	}
	

	public int getQtdeVaga() {
		return qtdeVaga;
	}

	public void setQtdeVaga(int qtdeVaga) {
		this.qtdeVaga = qtdeVaga;
	}

	public List<Curso> getCursos() {
		return cursos;
	}

	public void setCursos(List<Curso> cursos) {
		this.cursos = cursos;
	}

	public String getTelefoneContato() {
		return telefoneContato;
	}

	public void setTelefoneContato(String telefoneContato) {
		this.telefoneContato = telefoneContato;
	}

	public String getEmailContato() {
		return emailContato;
	}

	public void setEmailContato(String emailContato) {
		this.emailContato = emailContato;
	}
	
	public List<Aluno> getSelecionados() {
		return selecionados;
	}

	public void setSelecionados(List<Aluno> selecionados) {
		this.selecionados = selecionados;
	}
	
	public void addSelecionado(Aluno selecionado) throws Exception {
		if(this.selecionados.size() >= this.qtdeVaga)
			throw new Exception("Não há mais vagas na oferta de estágio!");
		
		this.selecionados.add(selecionado);
	}
	
	public void removerSelecionado(Aluno selecionado) {
		this.selecionados.remove(selecionado);
	}
	
	public boolean checkSelecionado(Object obj) {
		
		if(!(obj instanceof Aluno)) return false;
		
		for (Aluno aluno : selecionados) {
			
			if(aluno == (Aluno)obj){
				return true;
			}
		}
		
		return false;	
	}

	public List<Aluno> getCandidatos() {
		return candidatos;
	}

	public void setCandidatos(List<Aluno> candidatos) {
		this.candidatos = candidatos;
	}
	
	public void addRmCondidato(Aluno candidato){
		if(checkInscrito(String.valueOf(candidato.getId()))){
			this.removeCanditato(candidato);
		}else{
			this.addCandidato(candidato);
		}
	}
	
	public void addCandidato(Aluno candidato) {
		this.candidatos.add(candidato);
	}
	
	public void removeCanditato(Aluno candidato) {
		this.candidatos.remove(candidato);
	}
	
	public int totalCandidatos() {
		return this.candidatos.size();
	}

	public StatusOfertaEstagio getStatus() {
		return status;
	}

	public void setStatus(StatusOfertaEstagio status) {
		this.status = status;
	}

	public Date getVigencia() {
		return vigencia;
	}

	public void setVigencia(Date vigencia) {
		this.vigencia = vigencia;
	}

	public List<Estagio>  getEstagios() {
		return estagios;
	}

	public void setEstagios(List<Estagio> estagios) {
		this.estagios = estagios;
	}
	
	public Boolean checkInscrito(String id){
		Integer idNumerico= null;
		try{
			idNumerico = Integer.parseInt(id);
		}catch(NumberFormatException e){
			System.out.println("verifcar formato numérico");
			return false;
		}catch (Exception e) {
			System.out.println("verifcar formato numérico");
			return false;
		}
		
		for (Aluno aluno : candidatos) {
			
			if(aluno.getId() == idNumerico){
				return true;
			}
		}
		
		return false;
	}
}

src/main/java/br/edu/ifpb/sace/controllers/OfertaEstagioController.java
package br.edu.ifpb.sace.controllers;

import java.util.Collections;
import java.util.Map;

import br.edu.ifpb.sace.dao.EmpresaDAO;
import br.edu.ifpb.sace.dao.OfertaEstagioDAO;
import br.edu.ifpb.sace.dao.PersistenceUtil;
import br.edu.ifpb.sace.entity.Aluno;
import br.edu.ifpb.sace.entity.Empresa;
import br.edu.ifpb.sace.entity.OfertaEstagio;
import br.edu.ifpb.sace.facade.Categoria;
import br.edu.ifpb.sace.facade.Resultado;
import br.edu.ifpb.sace.util.StatusOfertaEstagio;
import br.edu.ifpb.sace.util.ValidatorType;
import br.edu.ifpb.sace.validators.domain.ConcretValidatorFactory;
import br.edu.ifpb.sace.validators.domain.IValidator;
import br.edu.ifpb.sace.validators.domain.IValidatorFactory;

public class OfertaEstagioController {
	
	public Resultado cadastrar(Map<String, String[]> parametros,Empresa empresa) throws Exception{
		Resultado resultado= new Resultado();
		OfertaEstagio ofertaEstagio;
		
		IValidatorFactory vf = new ConcretValidatorFactory(); 
		IValidator validador = vf.getValidatorType(ValidatorType.CADASTRO_OFERTA_ESTAGIO);
		
		if(validador.isValidParameters(parametros)){
			
			ofertaEstagio = (OfertaEstagio)validador.getResultado().getEntidade();
			empresa.addOfertaEstagio(ofertaEstagio);
			
			EmpresaDAO dao = new EmpresaDAO(PersistenceUtil.getCurrentEntityManager());
			dao.beginTransaction();
			
			if(ofertaEstagio.getId() == null) {
				dao.insert(empresa);
			} else{
				dao.update(empresa);
			}
			dao.commit();
			
			resultado.setErro(false);
			resultado.addMensagens(Collections.singletonList("Oferta criada com sucesso"),Categoria.INFO);
			resultado.setEntidade(ofertaEstagio);
		}else{
			resultado.setEntidade((OfertaEstagio)validador.getResultado().getEntidade());
			resultado.setErro(true);
			resultado.setMensagens(validador.getResultado().getMensagens());
			
		}
		return resultado;
	}
	
	public Resultado canceInscreverAluno(Map<String, String[]> parametros,Aluno aluno) throws Exception{
		
		Resultado resultado= new Resultado();
		OfertaEstagio ofertaEstagio;
		
		IValidatorFactory vf = new ConcretValidatorFactory(); 
		IValidator validador = vf.getValidatorType(ValidatorType.INS_CANC_ALUNO_OFERTA);
		
		if(validador.isValidParameters(parametros)){
			
			ofertaEstagio = (OfertaEstagio)validador.getResultado().getEntidade();

			if(ofertaEstagio == null){
				resultado.setErro(true);
				resultado.setMensagens(validador.getResultado().getMensagens());
			}else{
				ofertaEstagio.addRmCondidato(aluno);
				OfertaEstagioDAO dao = new OfertaEstagioDAO(PersistenceUtil.getCurrentEntityManager());
				dao.beginTransaction();
				dao.update(ofertaEstagio);
				dao.commit();
			}
		}
		
		return resultado;
		
	}
	
	public Resultado statusOfertaEstagio(Map<String, String[]> parametros,StatusOfertaEstagio status) throws Exception{
		
		Resultado resultado= new Resultado();
		OfertaEstagio ofertaEstagio;
		
		IValidatorFactory vf = new ConcretValidatorFactory(); 
		IValidator validador = vf.getValidatorType(ValidatorType.INS_CANC_ALUNO_OFERTA);
		
		if(validador.isValidParameters(parametros)){
			
			ofertaEstagio = (OfertaEstagio)validador.getResultado().getEntidade();

			if(ofertaEstagio == null){
				resultado.setErro(true);
				resultado.setMensagens(validador.getResultado().getMensagens());
			}else{
				ofertaEstagio.setStatus(status);
				OfertaEstagioDAO dao = new OfertaEstagioDAO(PersistenceUtil.getCurrentEntityManager());
				dao.beginTransaction();
				dao.update(ofertaEstagio);
				dao.commit();
			}
		}
		
		return resultado;
		
	}
	
public Resultado selecionarAluno(Map<String, String[]> parametros){
		
		Resultado resultado= new Resultado();
		OfertaEstagio ofertaEstagio = null;
		
		IValidatorFactory vf = new ConcretValidatorFactory(); 
		
		IValidator validador = null;
		try {
			validador = vf.getValidatorType(ValidatorType.SELECIONAR_ALUNO);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			return null;
		}
		
		if(validador.isValidParameters(parametros)){
			
			ofertaEstagio = (OfertaEstagio)validador.getResultado().getEntidade();
		}
		
		if(ofertaEstagio == null){
			resultado.setErro(true);
			resultado.setMensagens(validador.getResultado().getMensagens());
		}else{
			resultado.setMensagens(validador.getResultado().getMensagens());
			OfertaEstagioDAO dao = new OfertaEstagioDAO(PersistenceUtil.getCurrentEntityManager());
			dao.beginTransaction();
			dao.update(ofertaEstagio);
			dao.commit();
		}
		
		return resultado;
		
	}
}

src/main/webapp/pages/ofertaestagio/cadastro.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="mm" tagdir="/WEB-INF/tags/messages"%>
<%@taglib prefix="tt" tagdir="/WEB-INF/tags/templating"%>     

<tt:template title="Cadastro Oferta de Estágio">
	<jsp:attribute name="tscript">
	</jsp:attribute>
	<jsp:body>	
		<div class="container">
			<div class="jumbotron">
				<div class="row">
					<div class="col-sm-offset-3 col-md-6">
						<h3><img class="choose" src="${pageContext.request.contextPath}/assets/images/cadastro-estagio.png" >   Oportunidade de Estágio</h3>
					</div>	
				</div>
				<mm:messages value="${msgs}" erroStyle="color:red" infoStyle="color:blue"/>		
				<div class="row">	
					<form action="${pageContext.request.contextPath}/controller.do" method="POST" >
						<input type="hidden"name="op" value="cadoftest">
						<div class="row">	
						  <div class="form-group col-sm-offset-3 col-md-6">
						    <label for="titulo">Título</label>
						    <input type="text" name="titulo" value="${requestScope.ofertaEstagio.titulo}" class="form-control" id="nome" placeholder="Título">
						  </div>
						 </div> 
						<div class="row">
						  <div class="form-group col-sm-offset-3 col-md-6">
						    <label for="requisitos">Requisito</label>
						    <textarea  placeholder="Requisitos" name="requisitos" value="${requestScope.ofertaEstagio.requisito}" class="form-control" rows="3" id="requisito"></textarea>
						  </div>
					  	</div>
					  	<div class="row">
						  <div class="form-group col-sm-offset-3 col-md-6">
						    <label for="numvagas">Vagas disponíveis</label>
						    <input type="number" name="numvagas" value="${requestScope.ofertaEstagio.qtdeVaga}"  class="form-control" id="numvagas" placeholder="Vagas disponíveis">
						  </div>
					  	</div>
					  	<div class="row">
						  <div class="form-group col-sm-offset-3 col-md-6">
						    <label for="email">E-mail pra contato</label>
						    <input type="email" name="email" value="${requestScope.ofertaEstagio.emailContato}"  class="form-control" id="matrizcodigo" placeholder="E-mail pra contato">
						  </div>
					  	</div>
					  	<div class="row">
						  <div class="form-group col-sm-offset-3 col-md-6">
						    <label for="email">Bolsa</label>
						    <input name="bolsa" type="number" class="currency" max="2500.00" value="500.00" />
						  </div>
					  	</div>
					  	<div class="row">
						  <div class="form-group col-sm-offset-3 col-md-6">
						    <label for="cursos">Para os cursos</label>
						  	<select  multiple class="form-control" id="cursos" name="cursos[]">
								<c:forEach var="curso" items="${utilBean.cursos}">
									<option value="${curso.id}" label="${curso.nome}">${curso.nome}</option>
								</c:forEach>
							</select>
						  </div>
					  	</div>
				  		<div class="row">
					  		<div class="col-sm-offset-3">
					  			<button type="submit" class="btn btn-default">Salvar</button>
					  		</div>
				  		</div>
					</form>
				</div>
			</div>
		</div>	
		<script>
		(function($) {
			  $.fn.currencyInput = function() {
			    this.each(function() {
			      var wrapper = $("<div class='currency-input' />");
			      $(this).wrap(wrapper);
			      $(this).before("<span class='currency-symbol'>$</span>");
			      $(this).change(function() {
			        var min = parseFloat($(this).attr("min"));
			        var max = parseFloat($(this).attr("max"));
			        var value = this.valueAsNumber;
			        if(value < min)
			          value = min;
			        else if(value > max)
			          value = max;
			        $(this).val(value.toFixed(2)); 
			      });
			    });
			  };
			})(jQuery);

			$(document).ready(function() {
			  $('input.currency').currencyInput();
			});
		</script>
	</jsp:body>
</tt:template>

src/main/webapp/pages/ofertaestagio/gerencia.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="mm" tagdir="/WEB-INF/tags/messages"%>
<%@taglib prefix="tt" tagdir="/WEB-INF/tags/templating"%>     

<tt:template title="Cadastro Oferta de Estágio">
	<jsp:attribute name="tscript">
	</jsp:attribute>
	<jsp:body>	
		<div class="container">
			<div class="jumbotron">
				<div class="row">
					<div class="col-md-12 text-center">
						<h3>Ofertas de Estágio</h3>
						<hr/>
						<h6>Veja os candidatos as vagas de estágios listados abaixo</h6>
					</div>	
				</div>
				<mm:messages value="${msgs}"/>
				<div class="row">
					<div class="panel-group" id="accordion">
					<c:forEach var="oferta" items="${ofertaEstagioBean.getOfertasEstagio(sessionScope.usuario)}">
						  <div class="panel panel-default}">
						    <div class="panel-heading">
						    	<div class="row">
						    		<div class="col-md-10">
						    		<h4 class="panel-title">
								        <a data-toggle="collapse" data-parent="#accordion" href="#accordion${oferta.id}">
								        	${oferta.titulo}
								        </a>
								      </h4>
						    		</div>
						    		<c:if test="${oferta.status eq 'AGUARDANDO'}">
								    	<div class="col-md-2">
								    		<a class="btn btn-warning btn-xs disabled"><i class="glyphicon glyphicon-time"></i> Em Análise</a>
								    	</div>
							    	</c:if>
							    	<c:if test="${oferta.status eq 'NEGADO'}">
								    	<div class="col-md-2">
								    		<a class="btn btn-danger btn-xs disabled">Negado</a>
								    	</div>
							    	</c:if>		
							    	<c:if test="${oferta.status eq 'APROVADO'}">
							    		<div class="col-md-2">
							    			 <a class="btn btn-success btn-xs">
							    			 	<i class="glyphicon glyphicon-pencil"></i> Inscritos ${fn:length(oferta.candidatos)}
							    			 </a>
							    		</div>
						    		</c:if>
						    	</div>
						    </div>
						    <div id="accordion${oferta.id}" class="panel-collapse collapse in">
						      <div class="panel-body">
						      	<div class="row">
						      		<div class="col-md-11">
						      			<b>Função:</b> ${oferta.detalheFuncao}
						      		</div>
						      	</div>
						      	<div class="row">
						      		<div class="col-md-11">
						      			<b>Requisitos:</b> ${oferta.requisitos}
						      		</div>
						      	</div>
						      	<div class="row">
						      		<div class="col-md-2">
						      			<b>Valor da bolsa:</b> ${oferta.valorBolsa}
						      		</div>
						      		<div class="col-md-2">
						      			<b>Valor Benefício:</b> ${oferta.valorBenef}
						      		</div>
						      		<div class="col-md-2">
						      			<b>CH Semanais:</b> ${oferta.CHSemanais}
						      		</div>
						      		<div class="col-md-2">
						      			<b>Vagas:</b> ${oferta.qtdeVaga}
						      		</div>
						      		<div class="col-md-2">
						      			<b>Email Conato:</b> ${oferta.emailContato}
						      		</div>
						      	</div>
						      	<br>
						      	<c:if test="${fn:length(oferta.candidatos) gt 0}">
							      	<div class="row">
							      		<div class="col-md-12">
							      			<b>Condidatos Inscritos</b>
							      		</div>
							      		<hr />
							      	</div>
						      	</c:if> 
						      	<c:forEach var="candidato" items="${oferta.candidatos}">
								      <div class="row">
									      <div class="col-md-3">
										      <b>Nome:</b> ${candidato.nome}
									      </div>
									      <div class="col-md-3">
										      <b>Matrícula:</b> ${candidato.matricula}
									      </div>
									       <div class="col-md-offset-2 col-md-4">
									       	<div class="col-md-3">
										      	<button type="submit" class="btn btn-info btn-xs"><i class="glyphicon glyphicon-user"></i> Ver</button>
										      </div>
										      <c:if test="${not oferta.checkSelecionado(candidato)}">	
											      <div class="col-md-5">
												      <form action="${pageContext.request.contextPath}/controller.do" method="POST" >
												      	<input type="hidden" name="op" value="selalu"/>
												      	<input type="hidden" name="candidato" value="${candidato.id}"/>
												      	<input type="hidden" name="oferta" value="${oferta.id}"/>
												      	<button type="submit" class="btn btn-info btn-xs"><i class="glyphicon glyphicon-plus-sign"></i> selecionar</button>
												     </form>
											      </div>
										      </c:if>
										      <c:if test="${oferta.checkSelecionado(candidato)}">
											      <div class="col-md-2">
												      	<button type="button" class="btn btn-success btn-xs"><i class="glyphicon glyphicon-ok-sign"></i> selecionado</button>
											      </div>
											      <div class="col-md-offset-2 col-md-2">
											      	<form action="${pageContext.request.contextPath}/controller.do" method="POST" >
											      		<input type="hidden" name="op" value="novoest">
											      		<input type="hidden" name="candidato" value="${candidato.id}"/>
												      	<input type="hidden" name="oferta" value="${oferta.id}"/>
												      	<button type="submit" class="btn btn-warning btn-xs"><i class="glyphicon glyphicon-lock"></i> Novo Estágio</button>
											      	</form>
											      </div>
											 </c:if>
									       </div>
								      	</div>
						      		<hr />
						      	</c:forEach>
						      </div>
						    </div>
						  </div>
					</c:forEach>
					</div>	
				</div>
			</div>
		</div>	
	</jsp:body>
</tt:template>

src/main/webapp/pages/ofertaestagio/listagem.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="mm" tagdir="/WEB-INF/tags/messages"%>
<%@taglib prefix="tt" tagdir="/WEB-INF/tags/templating"%>     

<tt:template title="Cadastro Oferta de Estágio">
	<jsp:attribute name="tscript">
	</jsp:attribute>
	<jsp:body>	
		<div class="container">
			<div class="jumbotron">
				<div class="row">
					<div class="col-md-12 text-center">
						<h3><img class="choose" src="${pageContext.request.contextPath}/assets/images/lista.png" >   Ofertas de Estágio</h3>
						<hr/>
						<h6>Você pode inscrever-se nos estágios listados abaixo</h6>
					</div>	
				</div>
				<mm:messages value="${msgs}"/>	
				<div class="row">
					<div class="panel-group" id="accordion">
					<c:forEach var="oferta" items="${ofertaEstagioBean.ofertasEstagio}">
						<c:if test="${oferta.status eq 'APROVADO' or utilBean.instanceOf(sessionScope.usuario,'Coordenador')}">
						  <div class="panel panel-default ${oferta.checkSelecionado(sessionScope.usuario)?'candidato-selecionado':''}">
						    <div class="panel-heading">
						    	<div class="row">
						    		<div class="col-md-9">
						    		<h4 class="panel-title">
								        <a data-toggle="collapse" data-parent="#accordion" href="#accordion${oferta.id}">
								        	${oferta.titulo}
								        </a>
								      </h4>
						    		</div>
						    		<c:if test="${utilBean.instanceOf(sessionScope.usuario,'Aluno')}">
						    			<!-- ALUNO -->
						    			<div class="col-md-offset-1 col-md-1">
							    			<c:if test="${not oferta.checkInscrito(sessionScope.usuario.id)}">
							    				<form action="${pageContext.request.contextPath}/controller.do" method="POST">
							    					<input type="hidden"name="op" value="inscanccalu">
							    					<input type="hidden" name="oferta_estagio" value="${oferta.id}" />
							    					<button type="submit" class="btn btn-primary  btn-xs">Inscreva-se</button>
							    				</form>	
							    			</c:if>
							    		</div>
							    		<!-- ALUNO -->
							    		<div class="col-md-offset-1 col-md-2">	
							    			<c:if test="${oferta.checkInscrito(sessionScope.usuario.id) and not oferta.checkSelecionado(sessionScope.usuario)}">
							    				<form action="${pageContext.request.contextPath}/controller.do" method="POST">
							    					<input type="hidden"name="op" value="inscanccalu">
							    					<input type="hidden" name="oferta_estagio" value="${oferta.id}" />
							    					<button type="submit" class="btn btn-success btn-xs">Cancelar Inscrição</button>
							    				</form>	
							    			</c:if>	
						    			</div>
						    		</c:if>
						    		<!-- COORDENADOR -->
						    		<c:if test="${utilBean.instanceOf(sessionScope.usuario,'Coordenador') and oferta.status eq 'AGUARDANDO'}">
						    		<div class="col-md-offset-1 col-md-1">
						    			<form action="${pageContext.request.contextPath}/controller.do" method="POST">
							    			<input type="hidden"name="op" value="aproortu">
							    			<input type="hidden" name="oferta_estagio" value="${oferta.id}" />
							    			<button type="submit" class="btn btn-primary btn-xs">Aprovar</button>
							    		</form>
							    	</div>
							    	<div class="col-md-1">
							    		<form action="${pageContext.request.contextPath}/controller.do" method="POST">
							    			<input type="hidden"name="op" value="negoportu">
							    			<input type="hidden" name="oferta_estagio" value="${oferta.id}" />
							    			<button type="submit" class="btn btn-warning btn-xs">&nbsp;Negar&nbsp;</button>
							    		</form>	
						    		</div>
						    		</c:if>
						    		<!-- COORDENADOR -->
						    		<c:if test="${utilBean.instanceOf(sessionScope.usuario,'Coordenador')}">
						    			<c:if test="${oferta.status eq 'APROVADO'}">
							    			<div class="col-md-offset-1 col-md-1">
							    				<button type="button" class="btn btn-success btn-xs">Aprovado</button>
							    			</div>
						    			</c:if>
						    			<c:if test="${oferta.status eq 'NEGADO'}">
							    			<div class="col-md-offset-1 col-md-1">
							    				<button type="button" class="btn btn-warning btn-xs">&nbsp;Negado&nbsp;</button>
							    			</div>
						    			</c:if>
						    		</c:if>
						    	</div>
						    </div>
						    <div id="accordion${oferta.id}" class="panel-collapse collapse in">
						      <div class="panel-body">
						      	<div class="row">
						      		<div class="col-md-11">
						      			<b>Função:</b> ${oferta.detalheFuncao}
						      		</div>
						      	</div>
						      	<div class="row">
						      		<div class="col-md-11">
						      			<b>Requisitos:</b> ${oferta.requisitos}
						      		</div>
						      	</div>
						      	<div class="row">
						      		<div class="col-md-2">
						      			<b>Valor da bolsa:</b> ${oferta.valorBolsa}
						      		</div>
						      		<div class="col-md-2">
						      			<b>Valor Benefício:</b> ${oferta.valorBenef}
						      		</div>
						      		<div class="col-md-2">
						      			<b>CH Semanais:</b> ${oferta.CHSemanais}
						      		</div>
						      		<div class="col-md-2">
						      			<b>Vagas:</b> ${oferta.qtdeVaga}
						      		</div>
						      		<div class="col-md-2">
						      			<b>Email Conato:</b> ${oferta.emailContato}
						      		</div>
						      	</div>
						      	<div class="row">
						      		<br />
						      		<br />						
						      		<!-- ALUNO -->
							    	<div class="col-md-12">	
							    		<c:if test="${oferta.checkSelecionado(sessionScope.usuario)}">
							    			<div class="alert alert-success"><i class="glyphicon glyphicon-thumbs-up"></i> Parabéns você foi selecionado!</div>
							    		</c:if>	
						    		</div>
						      	</div>
						      </div>
						    </div>
						  </div>
						</c:if>
					</c:forEach>
					</div>	
				</div>
			</div>
		</div>	
	</jsp:body>
</tt:template>