src/main/java/br/edu/ifpb/sace/bean/UtilBean.java
package br.edu.ifpb.sace.bean;

import java.util.ArrayList;
import java.util.List;

import br.edu.ifpb.inheritance.Pessoa;
import br.edu.ifpb.sace.dao.CoordenadorDAO;
import br.edu.ifpb.sace.dao.CursoDAO;
import br.edu.ifpb.sace.dao.PersistenceUtil;
import br.edu.ifpb.sace.dao.PessoaDAO;
import br.edu.ifpb.sace.entity.Coordenador;
import br.edu.ifpb.sace.entity.Curso;
import br.edu.ifpb.sace.entity.Empresa;
import br.edu.ifpb.sace.entity.Regime;

public class UtilBean {
	
	public List<Regime> getRegime() {
		List<Regime> regime = new ArrayList<Regime>();
		regime.add(Regime.ANUAL);
		regime.add(Regime.BIMESTRAL);
		regime.add(Regime.SEMESTRAL);
		regime.add(Regime.MENSAL);
		regime.add(Regime.TRIMESTRAL);
		return regime;
	}
	
	public List<Coordenador> getCoordenadores() {
		CoordenadorDAO dao = new CoordenadorDAO(PersistenceUtil.getCurrentEntityManager());
		List<Coordenador> operadoras = dao.findAll();
		return operadoras;
	}
	
	public List<Curso> getCursos() {
		CursoDAO dao = new CursoDAO(PersistenceUtil.getCurrentEntityManager());
		List<Curso> cursos = dao.findAll();
		return cursos;
	}
	public List<Empresa> getEmpresas() {
	
		PessoaDAO dao = new PessoaDAO(PersistenceUtil.getCurrentEntityManager());
		List<Pessoa> pessoas = dao.findAll();
		List<Empresa> empresas = new ArrayList<Empresa>();
		for(Pessoa p: pessoas){
			System.out.println(p.getClass().getSimpleName());
			if(p.getClass().getSimpleName().equals("Empresa"))
				empresas.add((Empresa) p);
		}
		System.out.println(pessoas.size());
		return empresas;
	}


	public static boolean instanceOf(Object obj, String className) {
		return (obj.getClass().getSimpleName().equals(className))?true:false;
	}

}

src/main/java/br/edu/ifpb/sace/entity/Curso.java
package br.edu.ifpb.sace.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

@Entity
public class Curso {
	
	@Id
	@Column(name="CURSO_ID")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name="CODIGO")
	private int codigo;
	
	@Column(name="NOME")
	private String nome;
	
	@Column(name="DESCRICACAO")
	private String descricao;
	
	@Column(name="MATRIZ_CODIGO")
	private int matrizc;
	
	@Column(name="REGIME")
	private Enum regime;
	
	@OneToOne
	@JoinColumn(name="PESSOA_ID")
	private Coordenador Coordenador;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public int getMatrizc() {
		return matrizc;
	}

	public void setMatrizc(int matrizc) {
		this.matrizc = matrizc;
	}

	public Enum getRegime() {
		return regime;
	}

	public void setRegime(Enum regime) {
		this.regime = regime;
	}

	public Coordenador getCoordenador() {
		return Coordenador;
	}

	public void setCoordenador(Coordenador coordenador) {
		Coordenador = coordenador;
	}
	
}

src/main/java/br/edu/ifpb/sace/controllers/CursoController.java
package br.edu.ifpb.sace.controllers;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import br.edu.ifpb.sace.dao.CursoDAO;
import br.edu.ifpb.sace.dao.PersistenceUtil;
import br.edu.ifpb.sace.entity.Curso;
import br.edu.ifpb.sace.facade.Categoria;
import br.edu.ifpb.sace.facade.Resultado;
import br.edu.ifpb.sace.util.ValidatorType;
import br.edu.ifpb.sace.validators.domain.ConcretValidatorFactory;
import br.edu.ifpb.sace.validators.domain.IValidator;
import br.edu.ifpb.sace.validators.domain.IValidatorFactory;

public class CursoController {
	
	private Curso curso;
	private List<String> mensagensErro;
	
	@SuppressWarnings("unchecked")
	public Resultado cadastrar(Map<String, String[]> parametros) throws Exception{
		Resultado resultado= new Resultado();
		
		IValidatorFactory vf = new ConcretValidatorFactory(); 
		IValidator validador = vf.getValidatorType(ValidatorType.CADASTRO_CURSO);
		
		this.mensagensErro = new ArrayList<String>();
		
		if(validador.isValidParameters(parametros)){
			CursoDAO dao = new CursoDAO(PersistenceUtil.getCurrentEntityManager());
			dao.beginTransaction();
			
			if(this.curso.getId() == null) {
				dao.insert(this.curso);
			} else{
				dao.update(this.curso);
			}
			dao.commit();
			
			resultado.setErro(false);
			resultado.addMensagens(Collections.singletonList("Curso criado com sucesso"),Categoria.INFO);
			resultado.setEntidade(this.curso);
		}else{
			resultado.setEntidade(this.curso);
			resultado.setErro(true);
			
			this.mensagensErro = (List<String>) validador.getResultado();
			
			resultado.addMensagens(this.mensagensErro,Categoria.ERRO);
			
		}
		return resultado;
	}
	
}

src/main/webapp/pages/curso/cadastro.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="mm" tagdir="/WEB-INF/tags/messages"%>
<%@taglib prefix="tt" tagdir="/WEB-INF/tags/templating"%>     

<tt:template title="Cadastro Curso">
	<jsp:attribute name="tscript">
	</jsp:attribute>
	<jsp:body>	
		<div class="container">
			<div class="jumbotron">
				<div class="row">
					<div class="col-sm-offset-3 col-md-6">
						<h3>Dados do Curso</h3>
					</div>	
				</div>
				<div class="row">
					<div class="form-group col-sm-offset-3 col-md-6">
						<mm:messages value="${msgs}" erroStyle="color:red" infoStyle="color:blue"/>
					</div>	
				</div>		
				<div class="row">	
				<form action="${pageContext.request.contextPath}/controller.do" method="POST" >
					<input type="hidden"name="op" value="cadcur">
					<div class="row">	
					  <div class="form-group col-sm-offset-3 col-md-6">
					    <label for="nome">Nome</label>
					    <input type="text" name="nome" value="${requestScope.curso.nome}" class="form-control" id="nome" placeholder="Nome">
					  </div>
					 </div> 
					<div class="row">
					  <div class="form-group col-sm-offset-3 col-md-6">
					    <label for="codigo">Código</label>
					    <input type="text" name="codigo" value="${requestScope.curso.codigo}" class="form-control" id="codigo" placeholder="Código">
					  </div>
				  	</div>
				  	<div class="row">
					  <div class="form-group col-sm-offset-3 col-md-6">
					    <label for="matrizcodigo">Código Matriz</label>
					    <input type="text" name="matrizc" value="${requestScope.curso.matrizc}"  class="form-control" id="matrizcodigo" placeholder="Código Matriz">
					  </div>
				  	</div>
				  	<div class="row">
					  <div class="form-group col-sm-offset-3 col-md-6">
					    <label for="regime">Regime</label>
					  	<select class="form-control" id="regime" name="regime">
							<option value="${null}" label="Selecione o Regime">Selecione o Regime</option>
							<c:forEach var="regime" items="${utilBean.regime}">
								<option value="${regime}" label="${regime}">${regime}</option>
							</c:forEach>
						</select>
					  </div>
				  	</div>
				  		<div class="row">
					  <div class="form-group col-sm-offset-3 col-md-6">
					    <label for="coordenador">Coordenador(a)</label>
					   	<!--<select class="form-control" id="coordenador"></select>-->
					  	<select class="form-control" id="coordenador" name="coordenador">
							<option value="${null}" label="Selecione o Coordenador">Selecione o Coordenador</option>
							<c:forEach var="coordenador" items="${utilBean.coordenadores}">
								<option value="${coordenador.id}" label="${coordenador.nome}">${coordenador.nome}</option>
							</c:forEach>
						</select>
					  </div>
				  	</div>
				  	<div class="row">
					  <div class="form-group col-sm-offset-3 col-md-6">
					    <label for="descricao">Descrição</label>
					   	<textarea  name="descricao" value="${requestScope.curso.descricao}" class="form-control" rows="3" id="descricao"></textarea>
					  </div>
				  	</div>
				  	<div class="row">
				  		<div class="col-sm-offset-3">
				  			<button type="submit" class="btn btn-default">Salvar</button>
				  		</div>
				  	</div>
				</form>
				</div>	
			</div>
		</div>
	</jsp:body>
</tt:template>